### ISSUE TITLE
general fixes

### ISSUE THREAD

**Issue by abdelazizElemary** [AhmedElsayed200/Udemy-frontend-one-page-bldai#1]
- adjust disappearing of the header txt when minimizing the screen 

<img width="595" alt="Screen Shot 2022-08-11 at 11 17 43 AM" src="https://user-images.githubusercontent.com/25887879/184102305-e0906e9f-c83d-4e02-994e-4e2386f4cb0f.png">

- maximize the width of the main container 
- the courses in the `courses-card-container` align start them

**Comment by AhmedElsayed200** [comment]
I have fixed the first and third problems. Could you please declare to me the second problem again? I don't know what exactly is the main container.

**Comment by abdelazizElemary** [comment]
> I have fixed the first and third problems. Could you please declare to me the second problem again? I don't know what exactly is the main container.

The courses container

**Comment by AhmedElsayed200** [comment]
I have solved the issue and the course container is now taking 100% of the window's width
