### ISSUE TITLE
General fixes on phase 2 

### ISSUE THREAD

**Issue by abdelazizElemary** [AhmedElsayed200/Udemy-frontend-one-page-bldai#2]
- the search is not working
- grouping the courses not working when clicking on different types from the courses nav bar

**Comment by AhmedElsayed200** [comment]
Regarding the search: 
- If you write "Visualization" for example and press enter, only one course would appear. 
- If you write any keywords that are not related to any course title, all the courses would be displayed.
- If you delete your typed keywords and press enter, all the courses would be displayed.
Regarding the course grouping:
- Does this task related to phase 2? I thought that we only have to fetch course data from the JSON server and implement the search bar.

Could you please tell me if I have any miss understanding?
